trigger:
  branches:
    include:
      - main

pool:
  name: TestAgent

steps:

- script: |
    echo Python Version
    python --version
  displayName: Check Python

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: Install Dependencies

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: Archive App

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'connection1'
    appType: webAppLinux
    appName: 'testapp132'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
